version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py test utils
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db