# Generated by Django 3.1.5 on 2021-01-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='thread_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello_world.thread'),
        ),
    ]
