# Generated by Django 3.1.5 on 2021-02-07 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_auto_20210204_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='media',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
