# Generated by Django 3.1.5 on 2021-02-07 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_auto_20210207_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thread',
            name='media',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
