# Generated by Django 3.1.5 on 2021-02-08 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_auto_20210208_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_type',
            field=models.TextField(default='', max_length='24'),
        ),
        migrations.AddField(
            model_name='thread',
            name='media_type',
            field=models.TextField(default='', max_length='24'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 15, 34, 36, 209750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 15, 34, 36, 208750, tzinfo=utc)),
        ),
    ]
