# Generated by Django 3.1.5 on 2021-03-10 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0007_auto_20210304_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='priority',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 13, 41, 37, 833758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 13, 41, 37, 832758, tzinfo=utc)),
        ),
    ]
